# Generated by Django 2.1.15 on 2023-08-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='films',
        ),
    ]
