# Generated by Django 2.1.15 on 2023-08-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230803_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='date',
            new_name='distributeur',
        ),
    ]
