# Generated by Django 2.1.15 on 2023-08-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230803_1133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='films',
            new_name='Film',
        ),
    ]
